### ISSUE TITLE
zenvalidator.js throws error: Uncaught TypeError: $.entwine is not a function

### ISSUE THREAD

**Issue by TheRealAmplifier** [sheadawson/silverstripe-zenvalidator#75]
I've installed dev-master, but the module throws a gnarly error:
` Uncaught TypeError: $.entwine is not a function`

Is there an easy fix to get this module working on 4.5.* versions of SilverStripe?

**Comment by lekoala** [comment]
you need to call this

        ZenValidator::GlobalRequirements();

in your PageController init

this is due to the fact that you may already include jquery in other way, and entwine needs to be loaded after that. 

you can also load entwine like this

Requirements::javascript("sheadawson/silverstripe-zenvalidator:javascript/entwine/jquery.entwine-dist.js");

**Comment by TheRealAmplifier** [comment]
Thanks. this did the trick
